version: "3.7"

services:
  # MongoDB
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"

  # Backend API
  joyspot-api:
    container_name: backend
    build: ./
    command: npm run dev
    working_dir: /usr/src/joyspot-api
    depends_on:
      - mongodb
    ports:
      - "4000:4000"
    volumes:
      - ./:/usr/src/joyspot-api
